Nueva funcion clear_old_wizards
gisce/oopgrade pull request #25
Opened 2022-11-29 08:46 UTC by nvillarroya

Nueva función para borrar los wizards de v4

2022-12-12 18:14 UTC, guilleJB approved these changes

2022-12-12 18:54 UTC, tinogis requested changes

2022-12-12 18:54 UTC, tinogis commented on oopgrade/oopgrade.py
> +            imd_obj.unlink(cr, 1, model_id)
També s'ha d'esborrar de `ir.values` (si n'hi ha)

2022-12-29 15:47 UTC, ecarreras commented
Crec que s'hauria de passar tot a SQL per evitar tenir el pool, sino només ho podrem fer amb scripts `POST`

2023-01-25 08:08 UTC, merged