Eliminar los shortcuts de las vistas a eliminar
gisce/oopgrade pull request #45
Opened 2024-07-18 15:14 UTC by noone-is-taken

Se eliminan todas las vistas que usen la vista que se este eliminando en el método delete_record. Se buscan los shortcuts que usen la vista i se eliminan.

2024-07-18 15:38 UTC, polsala approved these changes

2024-07-23 19:04 UTC, polsala requested changes
ha nivel de "locks" en base de datos es mejor primero obtener los ids de los registros a eliminar y en caso de que haya registros a eliminar eliminarlos por id

2024-07-24 12:35 UTC, ecarreras approved these changes

2024-08-07 07:05 UTC, polsala approved these changes

2024-08-07 07:05 UTC, merged